version: 2

models: 
  - name: mart_housing_prices_breakdown
    config:
      tags: ['gold']
    description: Region-level summary of housing prices with urban/rural composition
    columns:
      - name: region
        description: Region name
        tests:
          - not_null
      - name: avg_price
        description: Average housing price in the region
        tests:
          - not_null
      - name: n_sales
        description: Number of sales (rows) for that region
        tests:
          - not_null 
  - name: region_type_composition
    config:
      tags: ['gold']
    description: Region-level breakdown of urban and rural location counts
    columns:
      - name: region
        description: Region name
        tests:
          - not_null
      - name: urban_count
        description: Number of urban locations in the region
        tests:
          - not_null
      - name: rural_count
        description: Number of rural locations in the region
        tests:
          - not_null
      - name: total_count
        description: Total number of locations in the region
        tests:
          - not_null
      - name: pct_urban
        description: Share of locations that are urban (0–1)
        tests:
          - not_null
  - name: region_type_composition_with_macro
    config:
      tags: ['gold']
    description: Region-level breakdown of urban and rural location counts
    columns:
      - name: region
        description: Region name
        tests:
          - not_null
      - name: urban_count
        description: Number of urban locations in the region
        tests:
          - not_null
      - name: rural_count
        description: Number of rural locations in the region
        tests:
          - not_null
      - name: total_locations
        description: Total number of locations in the region
        tests:
          - not_null
      - name: pct_urban
        description: Share of locations that are urban (0–1)
        tests:
          - not_null

exposures:
  - name: housing_dashboard
    type: dashboard
    depends_on:
      - ref('mart_housing_prices_breakdown')
    owner:
      name: BI Team
      email: bi@example.com
    url: https://metabase.example.com/dashboard/123
    description: >
      Daily housing market KPIs showing:
      - Average prices by region
      - Sales volume trends
      - Listing status distribution
    maturity: medium  # Options: low, medium, high