version: 2

models:
  - name: stg_housing_prices
    description: Staged housing prices with additional date dimensions
    columns:
      - name: id
        description: Unique identifier for each record
        tests:
          - not_null
      - name: date
        description: Date of the housing price record
        tests:
          - not_null
      - name: region
        description: Region/city where the house is located
        tests:
          - not_null
      - name: price
        description: Price of the house in the local currency
        tests:
          - not_null
      - name: year
        description: Year extracted from date
        tests:
          - not_null
      - name: month
        description: Month number (1-12) extracted from date
        tests:
          - not_null
          - accepted_values:
              values: [1,2,3,4,5,6,7,8,9,10,11,12]
      - name: day_of_week
        description: Day of week (0-6, where 0 is Sunday) extracted from date
        tests:
          - not_null
          - accepted_values:
              values: [0,1,2,3,4,5,6]

  - name: stg_location_data
    description: Staged location reference data with standardized formatting
    columns:
      - name: postcode
        description: Postal code (primary key)
        tests:
          - not_null
      - name: region
        description: Standardized region/city name in uppercase
        tests:
          - not_null
      - name: type
        description: Location type with proper capitalization
        tests:
          - not_null
      - name: type_normalized
        description: Location type with proper capitalization
        tests:
          - not_null
          - valid_values:
              valid_values: ['URBAN', 'RURAL', 'SUBURBAN']
          - accepted_values:
              values: ['URBAN', 'RURAL', 'SUBURBAN']