version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  dwh:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: dwh
    volumes:
      - postgres-db-volume-dwh:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.1-python3.10
    command: >
    bash -c "
      pip install --quiet --no-cache-dir -r /requirements.txt &&
      airflow db upgrade &&
      airflow users create \
        --username admin \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com \
        --password admin || true &&
      airflow scheduler & airflow webserver
    "
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__AUTHENTICATE: True
      AIRFLOW__WEBSERVER__AUTH_USER_REGISTRATION: False
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
      - airflow-logs:/opt/airflow/logs
    depends_on:
      - postgres

volumes:
  postgres-db-volume:
  postgres-db-volume-dwh:
  airflow-logs:
